# Generated by Django 5.1.5 on 2025-01-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_hours_per_week', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('nurse', 'Nurse'), ('activities', 'Activities'), ('hca', 'Healthcare Assistant'), ('chef', 'Chef'), ('kitchen_assistant', 'Kitchen Assistant')], max_length=50)),
                ('max_hours_per_week', models.PositiveIntegerField(default=40)),
                ('is_flexible', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department')),
            ],
        ),
    ]
