# Generated by Django 5.1.5 on 2025-01-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_flexible',
            new_name='avoid_holidays',
        ),
        migrations.RemoveField(
            model_name='department',
            name='max_hours_per_week',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_work_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='rotate_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_annual_leave',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='unauthorized_absences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='used_annual_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Sick', 'Sick'), ('Absent', 'Absent'), ('On Leave', 'On Leave')], max_length=50)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='schedule.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_sick', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schedule.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='schedule.employee')),
                ('replacement_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_shifts', to='schedule.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(related_name='employees', to='schedule.department'),
        ),
    ]
