# Generated by Django 5.1.5 on 2025-01-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_role_remove_employee_role_employee_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('required_employees', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requirements', to='schedule.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requirements', to='schedule.role')),
            ],
        ),
    ]
