# Generated by Django 5.1.5 on 2025-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_shiftrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
