# Generated by Django 5.1.5 on 2025-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_employee_work_end_time_employee_work_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_start_time',
        ),
        migrations.AddField(
            model_name='employee',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='Latest available time to work (leave blank for 24-hour availability).', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Earliest available time to work (leave blank for 24-hour availability).', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_work_any_time',
            field=models.BooleanField(default=False, help_text='Can this employee work at any time, including night shifts?'),
        ),
    ]
