# Generated by Django 5.1.5 on 2025-02-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_employee_on_holiday_employee_on_sick_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='avoid_holidays',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sick_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_annual_leave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='unauthorized_absences',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='used_annual_leave',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='replacement_employee',
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.employee'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='available_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='available_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_work_any_time',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='max_hours_per_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='on_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='on_sick_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='schedule.role'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.employee'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='required_employees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.department'),
        ),
    ]
