# Generated by Django 5.1.5 on 2025-02-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_employee_avoid_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='shifts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.shift'),
        ),
    ]
