# Generated by Django 5.1.5 on 2025-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_shiftrequirement_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='shifts',
        ),
    ]
