# Generated by Django 5.1.5 on 2025-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_shiftrequirement_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avoid_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_annual_leave',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='unauthorized_absences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='used_annual_leave',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
