# Generated by Django 5.1.5 on 2025-02-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_workday_remove_shift_is_sick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.role'),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
    ]
