# Generated by Django 5.1.5 on 2025-02-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_department_work_end_time_department_work_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='work_days',
            new_name='available_days',
        ),
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='shift_start_time',
        ),
        migrations.AddField(
            model_name='employee',
            name='max_hours_per_day',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_shift_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.CharField(choices=[('8-20', '8-20'), ('8-14', '8-14'), ('14-20', '14-20')], default='8-20', max_length=10),
        ),
    ]
