# Generated by Django 5.1.5 on 2025-02-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_rename_work_days_employee_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='total_hours_needed',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.CharField(choices=[('8-20', '8-20'), ('8-14', '8-14'), ('14-20', '14-20'), ('12-12', '12-12')], default='8-20', max_length=10),
        ),
    ]
