# Generated by Django 5.1.5 on 2025-02-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_remove_shiftrequirement_required_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.CharField(choices=[('08-20', '08-20'), ('8-14', '8-14'), ('14-20', '14-20')], default='12-12', max_length=10),
        ),
    ]
