# Generated by Django 5.1.5 on 2025-02-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_alter_shiftrequirement_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_work_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.CharField(choices=[('08-20', '08-20'), ('08-14', '08-14'), ('14-20', '14-20'), ('20-08', '20-08')], default='08-20', max_length=10),
        ),
    ]
