# Generated by Django 5.1.5 on 2025-02-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_employee_can_work_night_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='night_shift_hours_needed',
            field=models.IntegerField(default=12),
        ),
    ]
