# Generated by Django 5.1.5 on 2025-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_shiftrequirement_night_shift_hours_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_work_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
