# Generated by Django 5.1.5 on 2025-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_employee_can_work_full_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_work_partial_day',
            field=models.BooleanField(default=False),
        ),
    ]
