# Generated by Django 5.1.5 on 2025-02-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_remove_employee_can_work_partial_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hours',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('08-20', 'Full Day'), ('08-14', 'Morning'), ('14-20', 'Afternoon')], default='08-20', max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.employee'),
        ),
    ]
