# Generated by Django 5.1.5 on 2025-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_shift_hours_shift_shift_type_alter_shift_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='order',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0),
            preserve_default=False,
        ),
    ]
