# Generated by Django 5.1.5 on 2025-02-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_workday_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='order',
        ),
    ]
