# Generated by Django 5.1.5 on 2025-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_remove_workday_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('08-20', 'Full Day'), ('08-14', 'Morning'), ('14-20', 'Afternoon'), ('20-08', 'Night Shift'), ('09:30-14:30', 'Morning Extended'), ('09:00-17:00', 'Day Shift')], default='08-20', max_length=14),
        ),
    ]
