# Generated by Django 5.1.5 on 2025-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_alter_shift_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('08:00-20:00', '08:00 - 20:00'), ('08:00-14:00', '08:00 - 14:00'), ('14:00-20:00', '14:00 - 20:00'), ('20:00-08:00', '20:00 - 08:00'), ('09:30-14:30', '09:30 - 14:30'), ('09:00-17:00', '09:00 - 17:00')], default='08:00-20:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.CharField(choices=[('08:00-20:00', '08:00 - 20:00'), ('08:00-14:00', '08:00 - 14:00'), ('14:00-20:00', '14:00 - 20:00'), ('20:00-08:00', '20:00 - 08:00'), ('09:30-14:30', '09:30 - 14:30'), ('09:00-17:00', '09:00 - 17:00')], default='08:00-20:00', max_length=20),
        ),
    ]
